language: node_js
node_js:
  - '5'
before_install:
  - rm -rf node_modules
  - npm cache clean
script:
  - npm install
  - npm test
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - npm run coveralls
